# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "acpi_call" "tp_smapi" ];
  boot.extraModulePackages = [ 
    config.boot.kernelPackages.acpi_call
    config.boot.kernelPackages.tp_smapi
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bf0b73b1-ddb6-40cc-848b-15679da3aa04";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/ad60fa9a-718e-4d8f-837e-6cf220216f47";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D53A-75C7";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/swapfile"; } ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
